version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web:latest
    volumes:
      - ".:/app"
    command: "sh ./conf/start-cmd.sh"
    depends_on:
      - "redis"
      - "postgres"

  redis:
    image: redis:6.2.6
    restart: always
    volumes:
      - "redis:/data"

  nginx:
    image: nginx:1.21.3
    ports:
     - "8000:80"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./static:/app/static"
    restart: always
    depends_on:
      - "web"
  
  postgres:
    image: postgres:14.0
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  redis:
    driver: local
  postgres:
    driver: local
